/**
 * Custom Service Worker with Workbox + Background Sync
 * 
 * This service worker extends Workbox with custom background sync
 * functionality for photo uploads.
 */

/// <reference lib="webworker" />
import { clientsClaim } from 'workbox-core';
import { cleanupOutdatedCaches, precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { NetworkFirst, CacheFirst, StaleWhileRevalidate, NetworkOnly } from 'workbox-strategies';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';
import { ExpirationPlugin } from 'workbox-expiration';

declare const self: ServiceWorkerGlobalScope;

// Precache all assets generated by Vite build
precacheAndRoute(self.__WB_MANIFEST);

// Clean up outdated caches automatically
cleanupOutdatedCaches();

// Take control of all clients immediately
self.skipWaiting();
clientsClaim();

// ===========================
// Workbox Caching Strategies
// ===========================

// API calls - Network First with fallback to cache
registerRoute(
  ({ url }) => url.hostname.includes('supabase.co') && url.pathname.includes('/rest/'),
  new NetworkFirst({
    cacheName: 'supabase-api',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 5 * 60, // 5 minutes
      }),
    ],
    networkTimeoutSeconds: 10,
  })
);

// Auth endpoints - Network Only (never cache)
registerRoute(
  ({ url }) => url.hostname.includes('supabase.co') && url.pathname.includes('/auth/'),
  new NetworkOnly()
);

// Static assets (JS, CSS) - Cache First
registerRoute(
  ({ request }) => request.destination === 'script' || request.destination === 'style',
  new CacheFirst({
    cacheName: 'static-resources',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 60,
        maxAgeSeconds: 30 * 24 * 60 * 60, // 30 days
      }),
    ],
  })
);

// Images - Cache First
registerRoute(
  ({ request }) => request.destination === 'image',
  new CacheFirst({
    cacheName: 'images',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 30 * 24 * 60 * 60, // 30 days
      }),
    ],
  })
);

// Fonts - Cache First with long expiration
registerRoute(
  ({ request }) => request.destination === 'font',
  new CacheFirst({
    cacheName: 'fonts',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 30,
        maxAgeSeconds: 365 * 24 * 60 * 60, // 1 year
      }),
    ],
  })
);

// CDN resources - Stale While Revalidate
registerRoute(
  ({ url }) => url.origin.includes('cdn.'),
  new StaleWhileRevalidate({
    cacheName: 'cdn-resources',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 50,
        maxAgeSeconds: 7 * 24 * 60 * 60, // 7 days
      }),
    ],
  })
);

// ===========================
// Background Sync for Photos
// ===========================

/**
 * Background Sync event listener
 * 
 * Triggers when the browser determines the network is available
 * and a sync tag has been registered.
 */
self.addEventListener('sync', (event: any) => {
  console.log('[SW] Sync event received:', event.tag);
  
  if (event.tag === 'sync-photos') {
    event.waitUntil(syncPhotos());
  }
});

/**
 * Synchronize all pending photos from the cache
 */
async function syncPhotos(): Promise<void> {
  console.log('[SW] Starting photo sync...');
  
  try {
    const cache = await caches.open('pending-photos');
    const requests = await cache.keys();
    
    console.log(`[SW] Found ${requests.length} pending photos to sync`);
    
    let successCount = 0;
    let failedCount = 0;
    
    for (const request of requests) {
      try {
        const response = await cache.match(request);
        
        if (!response) {
          console.warn('[SW] No response found for request:', request.url);
          continue;
        }
        
        const photoData = await response.json();
        const { blob, bucket, path } = photoData;
        
        // Convert base64 data URL back to Blob
        const photoBlob = await dataUrlToBlob(blob);
        
        // Upload to Supabase Storage
        const uploadSuccess = await uploadPhotoToSupabase(
          photoBlob,
          bucket,
          path
        );
        
        if (uploadSuccess) {
          // Remove from cache on success
          await cache.delete(request);
          successCount++;
          console.log('[SW] Successfully uploaded photo:', path);
        } else {
          failedCount++;
          console.error('[SW] Failed to upload photo:', path);
        }
        
      } catch (error) {
        failedCount++;
        console.error('[SW] Error syncing photo:', error);
      }
    }
    
    console.log(`[SW] Photo sync complete. Success: ${successCount}, Failed: ${failedCount}`);
    
    // Notify clients about sync completion
    if (successCount > 0 || failedCount > 0) {
      await notifyClients({
        type: 'PHOTO_SYNC_COMPLETE',
        successCount,
        failedCount,
      });
    }
    
  } catch (error) {
    console.error('[SW] Failed to sync photos:', error);
    throw error;
  }
}

/**
 * Upload a photo to Supabase Storage
 */
async function uploadPhotoToSupabase(
  blob: Blob,
  bucket: string,
  path: string
): Promise<boolean> {
  try {
    const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
    const supabaseKey = import.meta.env.VITE_SUPABASE_ANON_KEY;
    
    if (!supabaseUrl || !supabaseKey) {
      console.error('[SW] Missing Supabase credentials in environment');
      return false;
    }
    
    // Upload to Supabase Storage using the REST API
    const uploadUrl = `${supabaseUrl}/storage/v1/object/${bucket}/${path}`;
    
    const response = await fetch(uploadUrl, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${supabaseKey}`,
        'Content-Type': blob.type || 'application/octet-stream',
      },
      body: blob,
    });
    
    if (!response.ok) {
      const errorText = await response.text();
      console.error('[SW] Upload failed:', response.status, errorText);
      return false;
    }
    
    console.log('[SW] Photo uploaded successfully to:', path);
    return true;
    
  } catch (error) {
    console.error('[SW] Error uploading photo to Supabase:', error);
    return false;
  }
}

/**
 * Notify all clients about an event
 */
async function notifyClients(message: any): Promise<void> {
  try {
    const clients = await self.clients.matchAll({ type: 'window', includeUncontrolled: true });
    
    clients.forEach((client) => {
      client.postMessage(message);
    });
    
  } catch (error) {
    console.error('[SW] Error notifying clients:', error);
  }
}

/**
 * Convert base64 data URL to Blob
 */
async function dataUrlToBlob(dataUrl: string): Promise<Blob> {
  const response = await fetch(dataUrl);
  return response.blob();
}

// ===========================
// Message Handler
// ===========================

/**
 * Handle messages from the main app
 */
self.addEventListener('message', (event) => {
  console.log('[SW] Message received:', event.data?.type);
  
  if (!event.data) return;
  
  if (event.data.type === 'QUEUE_PHOTO') {
    handleQueuePhoto(event.data.payload)
      .then(() => {
        event.ports[0]?.postMessage({ success: true });
      })
      .catch((error) => {
        console.error('[SW] Error queueing photo:', error);
        event.ports[0]?.postMessage({ success: false, error: error.message });
      });
  }
  
  if (event.data.type === 'TRIGGER_PHOTO_SYNC') {
    syncPhotos()
      .then(() => {
        event.ports[0]?.postMessage({ success: true });
      })
      .catch((error) => {
        console.error('[SW] Error triggering sync:', error);
        event.ports[0]?.postMessage({ success: false, error: error.message });
      });
  }
  
  if (event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});

/**
 * Queue a photo for background sync
 */
async function handleQueuePhoto(payload: any): Promise<void> {
  try {
    const cache = await caches.open('pending-photos');
    
    // Create a unique cache key
    const cacheKey = new Request(`/pending-photo/${payload.id}`);
    
    // Store photo data in cache
    const response = new Response(JSON.stringify(payload), {
      headers: { 'Content-Type': 'application/json' },
    });
    
    await cache.put(cacheKey, response);
    
    console.log('[SW] Photo queued for sync:', payload.path);
    
    // Try to register background sync
    try {
      const registration: any = self.registration;
      await registration.sync.register('sync-photos');
      console.log('[SW] Background sync registered');
    } catch (error) {
      console.warn('[SW] Background sync registration failed:', error);
      // Will sync on next activation or manual trigger
    }
    
  } catch (error) {
    console.error('[SW] Error queueing photo:', error);
    throw error;
  }
}

// Log service worker lifecycle events
self.addEventListener('install', () => {
  console.log('[SW] Service worker installed');
});

self.addEventListener('activate', () => {
  console.log('[SW] Service worker activated');
});

console.log('[SW] Custom service worker with background sync loaded');
