-- Alter table public.notas_entrada to add withholding tax fields
ALTER TABLE public.notas_entrada 
ADD COLUMN IF NOT EXISTS iss_retido NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS irrf_retido NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS csll_retido NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS pis_retido NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS cofins_retido NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS inss_retido NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS valor_liquido NUMERIC DEFAULT 0;

-- Alter table public.notas_saida to add withholding tax fields
ALTER TABLE public.notas_saida 
ADD COLUMN IF NOT EXISTS iss_retido NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS irrf_retido NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS csll_retido NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS pis_retido NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS cofins_retido NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS inss_retido NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS valor_liquido NUMERIC DEFAULT 0;
